/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_api_v1_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login For Access Token */
        post: operations["login_for_access_token_api_v1_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Access Token */
        post: operations["refresh_access_token_api_v1_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout User */
        post: operations["logout_user_api_v1_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Google Login */
        get: operations["google_login_api_v1_auth_google_login_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Google Callback */
        get: operations["google_callback_api_v1_auth_google_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Write User */
        post: operations["write_user_api_v1_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Current User */
        get: operations["read_current_user_api_v1_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memory/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Write Memory Ingest */
        post: operations["write_memory_ingest_api_v1_memory_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integrations/google/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Connect Google Integrations */
        get: operations["connect_google_integrations_api_v1_integrations_google_connect_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integrations/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Google Integrations Callback */
        get: operations["google_integrations_callback_api_v1_integrations_google_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integrations/google/{integration_type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Disconnect Google Integration */
        delete: operations["disconnect_google_integration_api_v1_integrations_google__integration_type__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/google/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Google Calendar Webhook */
        post: operations["google_calendar_webhook_api_v1_webhooks_google_calendar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/onboarding/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Onboarding
         * @description Same action serves the first automatic run (fired from the OAuth callback) and any
         *     later resume — always regenerates and overwrites the prior suggestion set.
         */
        post: operations["run_onboarding_api_v1_onboarding_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/onboarding/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Onboarding Status
         * @description `get_current_user` already returns the full raw dict including the three
         *     onboarding columns — no extra DB round trip needed.
         */
        get: operations["get_onboarding_status_api_v1_onboarding_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/onboarding/goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Onboarding Goals
         * @description Zero items in both lists is valid (onboarding is optional per-item) — still marks
         *     `completed`. `memory_record_id` stays `NULL` for every suggestion-derived goal —
         *     synthesis spans many extraction records, not one FK-able one.
         *
         *     A checked suggestion the user already has a goal for is not created again (its open
         *     match gets its blanks filled instead — core/goals/onboarding.py), so the response lists
         *     only newly created goals. Typed `additional_goals` are not deduped: like `POST /goals`,
         *     the user typed them on purpose.
         */
        post: operations["submit_onboarding_goals_api_v1_onboarding_goals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/telegram/link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Telegram Link Url */
        get: operations["read_telegram_link_url_api_v1_telegram_link_get"];
        put?: never;
        post?: never;
        /** Erase Telegram Link */
        delete: operations["erase_telegram_link_api_v1_telegram_link_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/telegram": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Telegram Webhook */
        post: operations["telegram_webhook_api_v1_webhooks_telegram_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integrations/notion/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Connect Notion Integration */
        get: operations["connect_notion_integration_api_v1_integrations_notion_connect_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integrations/notion/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Notion Integrations Callback */
        get: operations["notion_integrations_callback_api_v1_integrations_notion_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integrations/notion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Disconnect Notion Integration */
        delete: operations["disconnect_notion_integration_api_v1_integrations_notion_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/notion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Notion Webhook */
        post: operations["notion_webhook_api_v1_webhooks_notion_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Tasks */
        get: operations["read_tasks_api_v1_tasks_get"];
        put?: never;
        /** Write Task */
        post: operations["write_task_api_v1_tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Task */
        get: operations["read_task_api_v1_tasks__task_id__get"];
        put?: never;
        post?: never;
        /** Erase Task */
        delete: operations["erase_task_api_v1_tasks__task_id__delete"];
        options?: never;
        head?: never;
        /** Patch Task */
        patch: operations["patch_task_api_v1_tasks__task_id__patch"];
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Task Status */
        patch: operations["patch_task_status_api_v1_tasks__task_id__status_patch"];
        trace?: never;
    };
    "/api/v1/goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Goals
         * @description `status` takes several values (`?status=open&status=paused` for an "active goals"
         *     view). Newest first — the tasks list's "open first" trick relies on the alphabetical
         *     order of two statuses and doesn't work with four. Answers `304` when the browser's
         *     cached copy is still current (core/utils/etag.py).
         */
        get: operations["read_goals_api_v1_goals_get"];
        put?: never;
        /** Write Goal */
        post: operations["write_goal_api_v1_goals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/goals/{goal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Goal */
        get: operations["read_goal_api_v1_goals__goal_id__get"];
        put?: never;
        post?: never;
        /** Erase Goal */
        delete: operations["erase_goal_api_v1_goals__goal_id__delete"];
        options?: never;
        head?: never;
        /** Patch Goal */
        patch: operations["patch_goal_api_v1_goals__goal_id__patch"];
        trace?: never;
    };
    "/api/v1/goals/{goal_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Goal Status */
        patch: operations["patch_goal_status_api_v1_goals__goal_id__status_patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_login_for_access_token_api_v1_login_post */
        Body_login_for_access_token_api_v1_login_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /**
         * GoalCreate
         * @description Public input for `POST /goals`. `horizon: None` means "left empty — let the AI guess
         *     in the background" (core/goals/jobs.py). `source` is server-set (`"manual"`), never
         *     client-supplied.
         */
        GoalCreate: {
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Horizon */
            horizon?: ("short_term" | "long_term") | null;
            /** Target Date */
            target_date?: string | null;
        };
        /**
         * GoalDeletedRead
         * @description Response shape for `DELETE /goals/{id}`.
         */
        GoalDeletedRead: {
            /** Message */
            message: string;
        };
        /** GoalRead */
        GoalRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "open" | "paused" | "done" | "dropped";
            /**
             * Source
             * @enum {string}
             */
            source: "manual" | "conversation" | "email" | "calendar" | "notion";
            /** Horizon */
            horizon?: ("short_term" | "long_term") | null;
            /** Target Date */
            target_date?: string | null;
            /** Memory Record Id */
            memory_record_id?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Title Manually Set
             * @default false
             */
            title_manually_set: boolean;
            /**
             * Description Manually Set
             * @default false
             */
            description_manually_set: boolean;
        };
        /** GoalStatusUpdate */
        GoalStatusUpdate: {
            /**
             * Status
             * @enum {string}
             */
            status: "open" | "paused" | "done" | "dropped";
        };
        /**
         * GoalUpdate
         * @description Public input for `PATCH /goals/{id}`. `status` is deliberately absent — it changes
         *     only through `PATCH /goals/{id}/status`, the one place that enqueues Notion sync. An
         *     explicit `null` clears `description`/`horizon`/`target_date`, but is rejected for the
         *     non-nullable `title`.
         */
        GoalUpdate: {
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Horizon */
            horizon?: ("short_term" | "long_term") | null;
            /** Target Date */
            target_date?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthCheck */
        HealthCheck: {
            /** Status */
            status: string;
            /** Environment */
            environment: string;
            /** Version */
            version: string;
            /** Timestamp */
            timestamp: string;
        };
        /** MemoryExtractionRecordRead */
        MemoryExtractionRecordRead: {
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * Source Type
             * @enum {string}
             */
            source_type: "conversation" | "email" | "calendar" | "notion";
            /** Summary */
            summary: string;
            /** Source Channel */
            source_channel?: ("in_app" | "telegram") | null;
            /** Entities */
            entities?: {
                [key: string]: unknown;
            }[];
            /** Relationships */
            relationships?: {
                [key: string]: unknown;
            }[];
            /** Goals */
            goals?: {
                [key: string]: unknown;
            }[];
            /** Preferences */
            preferences?: {
                [key: string]: unknown;
            }[];
            /** Tasks */
            tasks?: {
                [key: string]: unknown;
            }[];
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /** MemoryIngestRequest */
        MemoryIngestRequest: {
            /**
             * Source Type
             * @enum {string}
             */
            source_type: "conversation" | "email" | "calendar" | "notion";
            /** Source Channel */
            source_channel?: ("in_app" | "telegram") | null;
            /**
             * Content
             * @example Remind me to send the invoice to Acme by Friday.
             */
            content: string;
        };
        /** OnboardingGoalsSubmitRequest */
        OnboardingGoalsSubmitRequest: {
            /** Checked Suggestions */
            checked_suggestions?: components["schemas"]["SuggestedGoal"][];
            /** Additional Goals */
            additional_goals?: components["schemas"]["SuggestedGoal"][];
        };
        /**
         * OnboardingStatusRead
         * @description Public response shape for `GET /onboarding/status` and `POST /onboarding/run`.
         */
        OnboardingStatusRead: {
            /**
             * Onboarding Status
             * @enum {string}
             */
            onboarding_status: "not_started" | "pending" | "ready" | "completed";
            /** Onboarding Suggested Goals */
            onboarding_suggested_goals?: {
                [key: string]: unknown;
            }[] | null;
            /** Onboarding Completed At */
            onboarding_completed_at?: string | null;
        };
        /** PaginatedListResponse[GoalRead] */
        PaginatedListResponse_GoalRead_: {
            /** Data */
            data: components["schemas"]["GoalRead"][];
            /** Total Count */
            total_count: number;
            /** Has More */
            has_more: boolean;
            /** Page */
            page?: number | null;
            /** Items Per Page */
            items_per_page?: number | null;
        };
        /** PaginatedListResponse[TaskRead] */
        PaginatedListResponse_TaskRead_: {
            /** Data */
            data: components["schemas"]["TaskRead"][];
            /** Total Count */
            total_count: number;
            /** Has More */
            has_more: boolean;
            /** Page */
            page?: number | null;
            /** Items Per Page */
            items_per_page?: number | null;
        };
        /** ReadyCheck */
        ReadyCheck: {
            /** Status */
            status: string;
            /** Environment */
            environment: string;
            /** Version */
            version: string;
            /** App */
            app: string;
            /** Database */
            database: string;
            /** Redis */
            redis: string;
            /** Timestamp */
            timestamp: string;
        };
        /**
         * SuggestedGoal
         * @description The one canonical shape for: the synthesis LLM's structured output, the JSONB
         *     persisted on `users.onboarding_suggested_goals`, and what the client posts to
         *     `POST /onboarding/goals`.
         */
        SuggestedGoal: {
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Horizon */
            horizon?: ("short_term" | "long_term") | null;
        };
        /**
         * TaskCreate
         * @description Public input for `POST /tasks`. Deliberately does not inherit `TaskBase`: `None`
         *     for `urgency`/`effort_level` means "left empty — let the AI guess in the background",
         *     which `TaskBase`'s `"medium"` default can't express. `source` is server-set
         *     (`"manual"`), never client-supplied. `goal_id` must be one of the user's own
         *     non-deleted goals.
         */
        TaskCreate: {
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Due Date */
            due_date?: string | null;
            /** Urgency */
            urgency?: ("low" | "medium" | "high") | null;
            /** Effort Level */
            effort_level?: ("deep_focus" | "light_focus" | "passive") | null;
            /** Goal Id */
            goal_id?: string | null;
        };
        /**
         * TaskDeletedRead
         * @description Response shape for `DELETE /tasks/{id}`.
         */
        TaskDeletedRead: {
            /** Message */
            message: string;
        };
        /** TaskRead */
        TaskRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Due Date */
            due_date?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "open" | "done";
            /**
             * Source
             * @enum {string}
             */
            source: "manual" | "conversation" | "email" | "calendar" | "notion";
            /**
             * Urgency
             * @enum {string}
             */
            urgency: "low" | "medium" | "high";
            /** Effort Level */
            effort_level?: ("deep_focus" | "light_focus" | "passive") | null;
            /** Memory Record Id */
            memory_record_id?: string | null;
            /** Scheduled Event Id */
            scheduled_event_id?: string | null;
            /** Goal Id */
            goal_id?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** TaskStatusUpdate */
        TaskStatusUpdate: {
            /**
             * Status
             * @enum {string}
             */
            status: "open" | "done";
        };
        /**
         * TaskUpdate
         * @description Public input for `PATCH /tasks/{id}`. `status` is deliberately absent — it changes
         *     only through `PATCH /tasks/{id}/status`, the one place that enqueues Notion sync.
         *     An explicit `null` clears `description`/`due_date`/`effort_level` and unlinks
         *     `goal_id`, but is rejected for the non-nullable `title`/`urgency`.
         */
        TaskUpdate: {
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Due Date */
            due_date?: string | null;
            /** Urgency */
            urgency?: ("low" | "medium" | "high") | null;
            /** Effort Level */
            effort_level?: ("deep_focus" | "light_focus" | "passive") | null;
            /** Goal Id */
            goal_id?: string | null;
        };
        /**
         * TelegramCallbackQuery
         * @description A quick-pick inline-keyboard button tap (see `core/telegram/client.py`'s
         *     `build_inline_keyboard`) — added for Feature 1.7's Notion clarification flow, whose
         *     quick-pick goal buttons need `allowed_updates=["message", "callback_query"]` at
         *     `setWebhook` time to actually be delivered.
         */
        TelegramCallbackQuery: {
            /** Id */
            id: string;
            /** Data */
            data?: string | null;
            message?: components["schemas"]["TelegramMessage"] | null;
        };
        /** TelegramChat */
        TelegramChat: {
            /** Id */
            id: number;
        };
        /**
         * TelegramLinkUrlRead
         * @description Response shape for `GET /telegram/link`.
         */
        TelegramLinkUrlRead: {
            /** Deep Link Url */
            deep_link_url: string;
        };
        /**
         * TelegramMessage
         * @description Only the fields this app actually reads out of Telegram's `Message` object.
         */
        TelegramMessage: {
            chat: components["schemas"]["TelegramChat"];
            /** Text */
            text?: string | null;
        };
        /**
         * TelegramUnlinkRead
         * @description Response shape for `DELETE /telegram/link`.
         */
        TelegramUnlinkRead: {
            /** Status */
            status: string;
        };
        /**
         * TelegramUpdate
         * @description Shape of a Telegram Bot API `Update` payload — `message` and `callback_query` are
         *     handled this slice (`allowed_updates=["message", "callback_query"]` at `setWebhook`
         *     time); `edited_message`/etc are never subscribed to, so they're not modeled here.
         */
        TelegramUpdate: {
            /** Update Id */
            update_id: number;
            message?: components["schemas"]["TelegramMessage"] | null;
            callback_query?: components["schemas"]["TelegramCallbackQuery"] | null;
        };
        /** Token */
        Token: {
            /** Access Token */
            access_token: string;
            /** Token Type */
            token_type: string;
        };
        /** UserCreate */
        UserCreate: {
            /**
             * First Name
             * @example Ada
             */
            first_name: string;
            /**
             * Last Name
             * @example Lovelace
             */
            last_name?: string | null;
            /**
             * Email
             * Format: email
             * @example ada@example.com
             */
            email: string;
            /**
             * Password
             * @example Str1ngst!
             */
            password: string;
            /**
             * Timezone
             * @default UTC
             * @example Africa/Lagos
             */
            timezone: string;
        };
        /**
         * UserRead
         * @description Public shape — never exposes `hashed_password` or `oauth_sub`.
         */
        UserRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * First Name
             * @example Ada
             */
            first_name: string;
            /**
             * Last Name
             * @example Lovelace
             */
            last_name?: string | null;
            /**
             * Email
             * Format: email
             * @example ada@example.com
             */
            email: string;
            /** Timezone */
            timezone: string;
            /** Is Superuser */
            is_superuser: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthCheck"];
                };
            };
        };
    };
    ready_api_v1_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyCheck"];
                };
            };
        };
    };
    login_for_access_token_api_v1_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_for_access_token_api_v1_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_access_token_api_v1_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
        };
    };
    logout_user_api_v1_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                refresh_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    google_login_api_v1_auth_google_login_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    google_callback_api_v1_auth_google_callback_get: {
        parameters: {
            query: {
                code: string;
                state: string;
            };
            header?: never;
            path?: never;
            cookie?: {
                oauth_state?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    write_user_api_v1_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_current_user_api_v1_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
        };
    };
    write_memory_ingest_api_v1_memory_ingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemoryIngestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryExtractionRecordRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    connect_google_integrations_api_v1_integrations_google_connect_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    google_integrations_callback_api_v1_integrations_google_callback_get: {
        parameters: {
            query: {
                code: string;
                state: string;
            };
            header?: never;
            path?: never;
            cookie?: {
                integrations_oauth_state?: string | null;
                refresh_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disconnect_google_integration_api_v1_integrations_google__integration_type__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                integration_type: "email" | "calendar";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    google_calendar_webhook_api_v1_webhooks_google_calendar_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Goog-Channel-Id"?: string | null;
                "X-Goog-Channel-Token"?: string | null;
                "X-Goog-Resource-State"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_onboarding_api_v1_onboarding_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnboardingStatusRead"];
                };
            };
        };
    };
    get_onboarding_status_api_v1_onboarding_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnboardingStatusRead"];
                };
            };
        };
    };
    submit_onboarding_goals_api_v1_onboarding_goals_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardingGoalsSubmitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_telegram_link_url_api_v1_telegram_link_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelegramLinkUrlRead"];
                };
            };
        };
    };
    erase_telegram_link_api_v1_telegram_link_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelegramUnlinkRead"];
                };
            };
        };
    };
    telegram_webhook_api_v1_webhooks_telegram_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Telegram-Bot-Api-Secret-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TelegramUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    connect_notion_integration_api_v1_integrations_notion_connect_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    notion_integrations_callback_api_v1_integrations_notion_callback_get: {
        parameters: {
            query: {
                code: string;
                state: string;
            };
            header?: never;
            path?: never;
            cookie?: {
                notion_integrations_oauth_state?: string | null;
                refresh_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disconnect_notion_integration_api_v1_integrations_notion_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    notion_webhook_api_v1_webhooks_notion_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    read_tasks_api_v1_tasks_get: {
        parameters: {
            query?: {
                page?: number;
                items_per_page?: number;
                status?: ("open" | "done") | null;
                urgency?: ("low" | "medium" | "high") | null;
                source?: ("manual" | "conversation" | "email" | "calendar" | "notion") | null;
                due_from?: string | null;
                due_to?: string | null;
                goal_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedListResponse_TaskRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    write_task_api_v1_tasks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_task_api_v1_tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    erase_task_api_v1_tasks__task_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDeletedRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_task_api_v1_tasks__task_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_task_status_api_v1_tasks__task_id__status_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskStatusUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_goals_api_v1_goals_get: {
        parameters: {
            query?: {
                page?: number;
                items_per_page?: number;
                status?: ("open" | "paused" | "done" | "dropped")[] | null;
                horizon?: ("short_term" | "long_term") | null;
                source?: ("manual" | "conversation" | "email" | "calendar" | "notion") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedListResponse_GoalRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    write_goal_api_v1_goals_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoalCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_goal_api_v1_goals__goal_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    erase_goal_api_v1_goals__goal_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalDeletedRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_goal_api_v1_goals__goal_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoalUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_goal_status_api_v1_goals__goal_id__status_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoalStatusUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
