"""create ingestion_sync

Revision ID: 116b6b923450
Revises: a1d91b329ac8
Create Date: 2026-09-09 00:00:00.000000

Hand-written, not autogenerated — matches established practice.
"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "116b6b923450"
down_revision: Union[str, None] = "a1d91b329ac8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "ingestion_sync",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("current_timestamp(0)"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("source_type", sa.String(length=20), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("content_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("memory_record_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["memory_record_id"], ["memory_extraction_record.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "source_type", "external_id", name="uq_ingestion_sync_user_source_external"),
    )
    op.create_index(op.f("ix_ingestion_sync_user_id"), "ingestion_sync", ["user_id"], unique=False)


def downgrade() -> None:
    op.drop_index(op.f("ix_ingestion_sync_user_id"), table_name="ingestion_sync")
    op.drop_table("ingestion_sync")
