"""create notion_connection, notion_shared_page, notion_block_sync, notion_block_link

Revision ID: 65a11312d511
Revises: d4f8b2a6c910
Create Date: 2026-09-23 00:00:00.000000

Hand-written, not autogenerated — matches every other migration in this repo. All four
tables land in one migration (mirrors `d4f8b2a6c910`'s precedent of multiple related
tables shipping together in the same slice).
"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "65a11312d511"
down_revision: Union[str, None] = "d4f8b2a6c910"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "notion_connection",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("current_timestamp(0)"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("access_token", sa.Text(), nullable=False),
        sa.Column("workspace_name", sa.String(length=255), nullable=True),
        sa.Column("connected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_notion_connection_user_id"), "notion_connection", ["user_id"], unique=True)

    op.create_table(
        "notion_shared_page",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("current_timestamp(0)"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("notion_page_id", sa.String(length=255), nullable=False),
        sa.Column("granted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "notion_page_id", name="uq_notion_shared_page_user_page"),
    )
    op.create_index(op.f("ix_notion_shared_page_user_id"), "notion_shared_page", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_notion_shared_page_notion_page_id"), "notion_shared_page", ["notion_page_id"], unique=False
    )

    op.create_table(
        "notion_block_sync",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("current_timestamp(0)"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("notion_block_id", sa.String(length=255), nullable=False),
        sa.Column("notion_page_id", sa.String(length=255), nullable=False),
        sa.Column("last_edited_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("content_fingerprint", sa.BigInteger(), nullable=False),
        sa.Column("clarification_requested_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "notion_block_id", name="uq_notion_block_sync_user_block"),
    )
    op.create_index(
        "ix_notion_block_sync_user_page", "notion_block_sync", ["user_id", "notion_page_id"], unique=False
    )

    op.create_table(
        "notion_block_link",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("current_timestamp(0)"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("notion_block_id", sa.String(length=255), nullable=False),
        sa.Column("item_type", sa.String(length=10), nullable=False),
        sa.Column("item_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "item_type", "item_id", name="uq_notion_block_link_user_item"),
    )
    op.create_index(
        "ix_notion_block_link_user_block", "notion_block_link", ["user_id", "notion_block_id"], unique=False
    )


def downgrade() -> None:
    op.drop_index("ix_notion_block_link_user_block", table_name="notion_block_link")
    op.drop_table("notion_block_link")

    op.drop_index("ix_notion_block_sync_user_page", table_name="notion_block_sync")
    op.drop_table("notion_block_sync")

    op.drop_index(op.f("ix_notion_shared_page_notion_page_id"), table_name="notion_shared_page")
    op.drop_index(op.f("ix_notion_shared_page_user_id"), table_name="notion_shared_page")
    op.drop_table("notion_shared_page")

    op.drop_index(op.f("ix_notion_connection_user_id"), table_name="notion_connection")
    op.drop_table("notion_connection")
