"""add onboarding fields to users

Revision ID: a1d91b329ac8
Revises: 19fcd1375166
Create Date: 2026-09-09 00:00:00.000000

Hand-written, not autogenerated — matches established practice. A second, separate
migration chained after the goals-table migration (one bounded schema unit per
migration, same convention as `b1e4f2a9c7d3`/`b4020f135620`).
"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a1d91b329ac8"
down_revision: Union[str, None] = "19fcd1375166"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "users", sa.Column("onboarding_status", sa.String(length=20), server_default="not_started", nullable=False)
    )
    op.add_column(
        "users", sa.Column("onboarding_suggested_goals", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    op.add_column("users", sa.Column("onboarding_completed_at", sa.DateTime(timezone=True), nullable=True))


def downgrade() -> None:
    op.drop_column("users", "onboarding_completed_at")
    op.drop_column("users", "onboarding_suggested_goals")
    op.drop_column("users", "onboarding_status")
