"""create memory_extraction_record, tasks, embeddings

Revision ID: b1e4f2a9c7d3
Revises: ffc94ea56c76
Create Date: 2026-09-08 00:00:00.000000

Hand-written, not autogenerated: `pgvector.sqlalchemy.Vector` has no Alembic
autogenerate renderer. Requires the `pgvector/pgvector:pg16` Postgres image (see
docker-compose.yml) — `CREATE EXTENSION vector` fails against a plain `postgres:16`.
"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b1e4f2a9c7d3"
down_revision: Union[str, None] = "ffc94ea56c76"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

EMBEDDING_DIMENSION = 384  # matches settings.EMBEDDING_DIMENSION / models/embedding.py


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.create_table(
        "memory_extraction_record",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("current_timestamp(0)"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("source_type", sa.String(length=20), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("source_channel", sa.String(length=20), nullable=True),
        sa.Column("entities", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("relationships", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("goals", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("preferences", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tasks", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_memory_extraction_record_user_id"), "memory_extraction_record", ["user_id"], unique=False
    )

    op.create_table(
        "tasks",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("current_timestamp(0)"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=10), server_default="open", nullable=False),
        sa.Column("memory_record_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("scheduled_event_id", sa.String(length=255), nullable=True),
        sa.Column("effort_level", sa.String(length=20), nullable=True),
        sa.Column("urgency", sa.String(length=10), server_default="medium", nullable=False),
        sa.Column("urgency_manually_set", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["memory_record_id"], ["memory_extraction_record.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tasks_user_id"), "tasks", ["user_id"], unique=False)
    op.create_index(op.f("ix_tasks_memory_record_id"), "tasks", ["memory_record_id"], unique=False)

    op.create_table(
        "embeddings",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("current_timestamp(0)"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("memory_record_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("embedding", Vector(EMBEDDING_DIMENSION), nullable=False),
        sa.ForeignKeyConstraint(["memory_record_id"], ["memory_extraction_record.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_embeddings_memory_record_id"), "embeddings", ["memory_record_id"], unique=True
    )
    # IVFFlat cosine index — lists=100 is an arbitrary starting value (rule of thumb is
    # roughly sqrt(row count); revisit once real row counts exist).
    op.execute(
        "CREATE INDEX ix_embeddings_embedding_cosine ON embeddings "
        "USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100)"
    )


def downgrade() -> None:
    op.drop_table("embeddings")

    op.drop_index(op.f("ix_tasks_memory_record_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_user_id"), table_name="tasks")
    op.drop_table("tasks")

    op.drop_index(op.f("ix_memory_extraction_record_user_id"), table_name="memory_extraction_record")
    op.drop_table("memory_extraction_record")

    # Deliberately not dropping the `vector` extension itself — other data/objects may
    # depend on it, and `CREATE EXTENSION IF NOT EXISTS` on a future upgrade is a no-op.
