"""create integration_connection

Revision ID: b4020f135620
Revises: b1e4f2a9c7d3
Create Date: 2026-09-09 00:00:00.000000

Hand-written, not autogenerated — matches established practice (both prior migrations
are hand-written too).
"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b4020f135620"
down_revision: Union[str, None] = "b1e4f2a9c7d3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "integration_connection",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("current_timestamp(0)"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("access_token", sa.Text(), nullable=False),
        sa.Column("connected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("external_account_identifier", sa.String(length=255), nullable=True),
        sa.Column("refresh_token", sa.Text(), nullable=True),
        sa.Column("token_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scopes", sa.String(length=500), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("watch_channel_id", sa.String(length=255), nullable=True),
        sa.Column("watch_resource_id", sa.String(length=255), nullable=True),
        sa.Column("watch_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("history_id", sa.String(length=50), nullable=True),
        sa.Column("channel_token", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "type", "provider", name="uq_integration_connection_user_type_provider"),
    )
    op.create_index(op.f("ix_integration_connection_user_id"), "integration_connection", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_integration_connection_external_account_identifier"),
        "integration_connection",
        ["external_account_identifier"],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index(op.f("ix_integration_connection_external_account_identifier"), table_name="integration_connection")
    op.drop_index(op.f("ix_integration_connection_user_id"), table_name="integration_connection")
    op.drop_table("integration_connection")
