"""add soft delete + sticky override flags to tasks

Revision ID: c3a7e19d52f8
Revises: 65a11312d511
Create Date: 2026-09-24 00:00:00.000000

Hand-written, not autogenerated — matches every other migration in this repo. `tasks` may
already hold rows, so every new NOT NULL boolean carries `server_default=false` (same as
`urgency_manually_set` in `b1e4f2a9c7d3`).
"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c3a7e19d52f8"
down_revision: Union[str, None] = "65a11312d511"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("tasks", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("tasks", sa.Column("is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False))
    op.add_column(
        "tasks",
        sa.Column("effort_level_manually_set", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    op.add_column(
        "tasks", sa.Column("title_manually_set", sa.Boolean(), server_default=sa.text("false"), nullable=False)
    )
    op.add_column(
        "tasks",
        sa.Column("description_manually_set", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )


def downgrade() -> None:
    op.drop_column("tasks", "description_manually_set")
    op.drop_column("tasks", "title_manually_set")
    op.drop_column("tasks", "effort_level_manually_set")
    op.drop_column("tasks", "is_deleted")
    op.drop_column("tasks", "deleted_at")
