"""create telegram_link, conversation_message

Revision ID: d4f8b2a6c910
Revises: 116b6b923450
Create Date: 2026-09-14 00:00:00.000000

Hand-written, not autogenerated — matches every other migration in this repo. Both
tables land in one migration (mirrors `b1e4f2a9c7d3`'s precedent of multiple related
tables shipping together in the same slice).
"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d4f8b2a6c910"
down_revision: Union[str, None] = "116b6b923450"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "telegram_link",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("current_timestamp(0)"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("telegram_chat_id", sa.BigInteger(), nullable=False),
        sa.Column("linked_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consecutive_failure_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_failure_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_telegram_link_user_id"), "telegram_link", ["user_id"], unique=True)
    op.create_index(op.f("ix_telegram_link_telegram_chat_id"), "telegram_link", ["telegram_chat_id"], unique=True)

    op.create_table(
        "conversation_message",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("current_timestamp(0)"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("role", sa.String(length=10), nullable=False),
        sa.Column("channel", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_conversation_message_user_id"), "conversation_message", ["user_id"], unique=False)
    op.create_index("ix_conversation_message_created_at", "conversation_message", ["created_at"], unique=False)


def downgrade() -> None:
    op.drop_index("ix_conversation_message_created_at", table_name="conversation_message")
    op.drop_index(op.f("ix_conversation_message_user_id"), table_name="conversation_message")
    op.drop_table("conversation_message")

    op.drop_index(op.f("ix_telegram_link_telegram_chat_id"), table_name="telegram_link")
    op.drop_index(op.f("ix_telegram_link_user_id"), table_name="telegram_link")
    op.drop_table("telegram_link")
