"""goal tracking: goal soft delete + sticky flags, drop goals.due_date, tasks.goal_id

Revision ID: e5d1a8c3b947
Revises: c3a7e19d52f8
Create Date: 2026-09-24 00:00:00.000000

Hand-written, not autogenerated — matches every other migration in this repo. Both tables
may already hold rows, so every new NOT NULL boolean carries `server_default=false`. The
new goal statuses (`paused`/`dropped`) need no DB change: `goals.status` is a plain
String(10) with no constraint. Downgrade re-adds `goals.due_date` empty — its old values are
gone (no real user data exists yet, decisions-log.md 2026-09-24).
"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e5d1a8c3b947"
down_revision: Union[str, None] = "c3a7e19d52f8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("goals", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("goals", sa.Column("is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False))
    op.add_column(
        "goals", sa.Column("title_manually_set", sa.Boolean(), server_default=sa.text("false"), nullable=False)
    )
    op.add_column(
        "goals",
        sa.Column("description_manually_set", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    op.drop_column("goals", "due_date")

    op.add_column("tasks", sa.Column("goal_id", postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key("fk_tasks_goal_id_goals", "tasks", "goals", ["goal_id"], ["id"], ondelete="SET NULL")
    op.create_index(op.f("ix_tasks_goal_id"), "tasks", ["goal_id"], unique=False)
    op.add_column(
        "tasks", sa.Column("goal_id_manually_set", sa.Boolean(), server_default=sa.text("false"), nullable=False)
    )


def downgrade() -> None:
    op.drop_column("tasks", "goal_id_manually_set")
    op.drop_index(op.f("ix_tasks_goal_id"), table_name="tasks")
    op.drop_constraint("fk_tasks_goal_id_goals", "tasks", type_="foreignkey")
    op.drop_column("tasks", "goal_id")

    op.add_column("goals", sa.Column("due_date", sa.Date(), nullable=True))
    op.drop_column("goals", "description_manually_set")
    op.drop_column("goals", "title_manually_set")
    op.drop_column("goals", "is_deleted")
    op.drop_column("goals", "deleted_at")
